### ISSUE TITLE
Error on some apks when running FlowDroid either from command line and programmatically

### ISSUE THREAD

**Issue by LouisonGitzinger** [secure-software-engineering/FlowDroid#43]
Hi there, 

I'm experiencing a new error on multiples when running FlowDroid on it : 
```Java
[main] INFO soot.jimple.infoflow.android.SetupApplication - Constructing the callgraph...
[main] INFO soot.jimple.infoflow.android.callbacks.DefaultCallbackAnalyzer - Running incremental callback analysis for 9 components...
[main] INFO soot.jimple.infoflow.android.callbacks.DefaultCallbackAnalyzer - Incremental callback analysis done.
[main] INFO soot.jimple.infoflow.memory.MemoryWarningSystem - Shutting down the memory warning system...
The data flow analysis has failed. Error message: not declared: dummyMainMethod_m
java.lang.RuntimeException: not declared: dummyMainMethod_m
	at soot.SootMethod.getDeclaringClass(SootMethod.java:220)
	at soot.jimple.infoflow.android.entryPointCreators.AndroidEntryPointCreator.removeGeneratedMethods(AndroidEntryPointCreator.java:551)
	at soot.jimple.infoflow.android.SetupApplication.createEntryPointCreator(SetupApplication.java:1553)
	at soot.jimple.infoflow.android.SetupApplication.createMainMethod(SetupApplication.java:1034)
	at soot.jimple.infoflow.android.SetupApplication.calculateCallbackMethods(SetupApplication.java:685)
	at soot.jimple.infoflow.android.SetupApplication.calculateCallbacks(SetupApplication.java:494)
	at soot.jimple.infoflow.android.SetupApplication.calculateCallbacks(SetupApplication.java:462)
	at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1385)
	at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1318)
	at soot.jimple.infoflow.cmd.MainClass.run(MainClass.java:236)
	at soot.jimple.infoflow.cmd.MainClass.main(MainClass.java:196)
```
No idea from where the error comes from.
Here is the apk on which I have the error : 
[https://transfer.sh/Mqolf/test.apk](https://transfer.sh/Mqolf/test.apk)

Thank you in advance !

**Comment by StevenArzt** [comment]
Thanks for pointing this out, this was indeed a bug. I have fixed the problem, the app now works for me.

**Comment by Leetsong** [comment]
@StevenArzt I'm using FlowDroid 2.6-SNAPSHOT, I'm still having the problem!

```
java.lang.RuntimeException: not declared: dummyMainMethod_ParentActivity
	at soot.SootMethod.getDeclaringClass(SootMethod.java:220)
	at soot.jimple.infoflow.android.entryPointCreators.AndroidEntryPointCreator.removeGeneratedMethods(AndroidEntryPointCreator.java:551)
	at soot.jimple.infoflow.android.SetupApplication.createEntryPointCreator(SetupApplication.java:1555)
	at soot.jimple.infoflow.android.SetupApplication.createMainMethod(SetupApplication.java:1035)
	at soot.jimple.infoflow.android.SetupApplication.calculateCallbackMethods(SetupApplication.java:686)
	at soot.jimple.infoflow.android.SetupApplication.calculateCallbacks(SetupApplication.java:495)
	at soot.jimple.infoflow.android.SetupApplication.calculateCallbacks(SetupApplication.java:463)
	at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1386)
	at soot.jimple.infoflow.android.SetupApplication.runInfoflow(SetupApplication.java:1319)
```

Here is the apk.
https://github.com/wordpress-mobile/WordPress-Android/releases/download/10.1/wpandroid-10.2-rc-1.apk

Thanks!

**Comment by StevenArzt** [comment]
The line numbers appear to be from an outdated version of FlowDroid. I also tried to reproduce the problem with the newest version (2.6.1), and the data flow analysis runs just fine on the "wpandroid" APK. Can you make sure that you actually have the most recent version?
